## Count the Battleships

**There are three kinds of battleships: Destroyers, Submarines and Patrols in a game board of size $M \times N$.** The objective is to count the number of Destroyers, Submarines and Patrols in the board.

In [2]:
import numpy as np

In [1]:
def convert_board(board):
    N = len(board)
    M = len(board[0])
    A = np.zeros((N,M))
    for i in range(N):
        for j in range(M):
            if board[i][j] == '#':
                A[i,j] = 1
            else:
                A[i,j] = 0
    return np.array(A)

### Battleship: Destroyers

In [23]:
Destroyers = [".##..","#.#..","#....","#...."]
convert_board(Destroyers)

array([[0., 1., 1., 0., 0.],
       [1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.]])

In [26]:
Destroyers = ["..##.","..#..",".....","###.."]
convert_board(Destroyers)

array([[0., 0., 1., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [27]:
count_the_shape(Destroyers)

{'Destroyers': 2, 'Submarines': 0, 'Patrol Boats': 0.0}

### Battleship: Submarines

In [29]:
Submarines = ["..##.",".....",".....","##..."]
convert_board(Submarines)

array([[0., 0., 1., 1., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

In [30]:
count_the_shape(Submarines)

{'Destroyers': 0, 'Submarines': 2, 'Patrol Boats': 0.0}

### Battleship: Patrol Boats

In [33]:
Patrols = [".#...","....#","#....","..#.."]
convert_board(Patrols)

array([[0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [34]:
count_the_shape(Patrols)

{'Destroyers': 0, 'Submarines': 0, 'Patrol Boats': 4.0}

In [3]:
def two_by_two_filter(board):
    N,M = board.shape
    ct = 0
    for i in range(N-1):
        for j in range(M-1):
            if board[i,j]+board[i,j+1]+board[i+1,j]+board[i+1,j+1]==3:
                ct =ct+1
    return ct

In [4]:
def three_by_one_filter(board):
    N,M = board.shape
    ct = 0
    for i in range(N-2):
        for j in range(M):
            if board[i,j]+board[i+1,j]+board[i+2,j]==3:
                ct = ct+1
    return ct

In [5]:
def one_by_three_filter(board):
    N,M = board.shape
    ct = 0
    for i in range(N):
        for j in range(M-2):
            if board[i,j]+board[i,j+1]+board[i,j+2] == 3:
                ct = ct+1
    return ct

In [6]:
def two_by_one_filter(board):
    N,M = board.shape
    ct = 0
    for i in range(N-1):
        for j in range(M):
            if board[i,j]+board[i+1,j]==2:
                ct = ct+1
    return ct

In [7]:
def one_by_two_filter(board):
    N,M = board.shape
    ct = 0
    for i in range(N):
        for j in range(M-1):
            if board[i,j]+board[i,j+1]==2:
                ct = ct+1
    return ct

In [8]:
def count_the_shape(board):
    board = convert_board(board)
    A = two_by_two_filter(board)
    B = three_by_one_filter(board)
    C = one_by_three_filter(board)
    D = two_by_one_filter(board)
    E = one_by_two_filter(board)
    output = {}
    output['Destroyers'] = A + B + C
    output['Submarines'] = D - A - 2*B + E - A - 2*C
    output['Patrol Boats'] = np.sum(board) - 3*output['Destroyers'] - 2*output['Submarines']
    return output

In [11]:
count_the_shape(board)

{'Destroyers': 2, 'Submarines': 1, 'Patrol Boats': 2.0}

In [12]:
board = [".##.#","#.#..","#...#","#.##."]
convert_board(board)

array([[0., 1., 1., 0., 1.],
       [1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1.],
       [1., 0., 1., 1., 0.]])

In [13]:
count_the_shape(board)

{'Destroyers': 2, 'Submarines': 1, 'Patrol Boats': 2.0}

In [14]:
board = [".#..#","##..#","...#."]
convert_board(board)

array([[0., 1., 0., 0., 1.],
       [1., 1., 0., 0., 1.],
       [0., 0., 0., 1., 0.]])

In [15]:
count_the_shape(board)

{'Destroyers': 1, 'Submarines': 1, 'Patrol Boats': 1.0}

In [46]:
board = ["##.","#.#",".##"]
count_the_shape(board)

{'Destroyers': 2, 'Submarines': 0, 'Patrol Boats': 0.0}

In [47]:
board = ["...","...","..."]
count_the_shape(board)

{'Destroyers': 0, 'Submarines': 0, 'Patrol Boats': 0.0}